version: "3.7"

services:
  web:
    image: jensgertsen/sparktest:v0.0.1
    user: 1000:1000
    restart: on-failure
    stop_grace_period: 1m
    ports:
      - 21214:21214
    volumes:
      - ${APP_DATA_DIR}/data:/data
      - ${LND_DATA_DIR}:/lnd:ro
    environment:
      # Global
      LNBITS_BIND: "0.0.0.0:$APP_LNBITS_PORT"
      LNBITS_DATA_FOLDER: "/data"

      # LND
      LND_GRPC_ENDPOINT: $LND_IP
      LND_GRPC_PORT: $LND_GRPC_PORT
      LND_GRPC_CERT: "/lnd/tls.cert"
      LND_GRPC_MACAROON: "/lnd/data/chain/bitcoin/$BITCOIN_NETWORK/admin.macaroon"

      # App
      